# Generated by Django 4.1.6 on 2023-02-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=25)),
                ('tipoproblema', models.CharField(max_length=25)),
                ('problema', models.CharField(max_length=25)),
            ],
        ),
    ]
