# Generated by Django 4.1.6 on 2023-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
    ]
