# Generated by Django 4.1.6 on 2023-03-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_categoriaplato_cliente_pedido_usuarior_plato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigopedido', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('Con el repartidor', 'Con el repartidor'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], max_length=20)),
                ('plato', models.CharField(max_length=3)),
                ('valor', models.CharField(max_length=3)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.restaurante')),
            ],
        ),
    ]
